server:
  port: 8082

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myTest?useUnicode=true&characterEncoding=UTF-8&PublicKeyRetrieval=true&&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
